import Pagination from '../../components/Pagination'
import { useState } from 'react'
import SubLayout from '../../components/SubLayout'

const menus = [
  { label: '교회소식',   path: '/community/news' },
  { label: '주보보기',   path: '/community/bulletin' },
  { label: '행사갤러리', path: '/community/gallery' },
  { label: '행사동영상', path: '/community/video' },
  { label: '새가족소개', path: '/community/newcomer' },
  { label: '부서자료실', path: '/community/resources' },
  { label: '공지사항',   path: '/community/notice' },
  { label: '영선관리',   path: '/community/farm' },
]

const PER_PAGE = 12

const photos = [
  { src: '/images/community/gallery_1006.jpg', label: '농장부비닐작업및감자씨심기' },
  { src: '/images/community/gallery_1005.jpg', label: '교육부토요활동' },
  { src: '/images/community/gallery_1004.jpg', label: '이웃나눔(생선구이)' },
  { src: '/images/community/gallery_1003.jpg', label: '농장부헌신예배' },
  { src: '/images/community/gallery_1002.jpg', label: '아동부-이*아생일파티' },
  { src: '/images/community/gallery_981.jpg', label: '구역장모임공과공부(매주수요일)' },
  { src: '/images/community/gallery_980.jpg', label: '밭밑거름뿌리기작업' },
  { src: '/images/community/gallery_979.jpg', label: '26년춘계대심방' },
  { src: '/images/community/gallery_978.jpg', label: '매주목요일전도활동' },
  { src: '/images/community/gallery_977.jpg', label: '아동부왕곡천전도활동' },
  { src: '/images/community/gallery_976.jpg', label: '권사회-오곡밥과나물 준비' },
  { src: '/images/community/gallery_975.jpg', label: '전교인윷놀이한마당(밤굽기)' },
  { src: '/images/community/gallery_974.jpg', label: '아동부밤굽기' },
  { src: '/images/community/gallery_973.jpg', label: '26년직분자교육 (최선규안수집사)' },
  { src: '/images/community/gallery_972.jpg', label: '설명절음식준비' },
  { src: '/images/community/gallery_971.jpg', label: '설-명절이웃나눔' },
  { src: '/images/community/gallery_970.jpg', label: '교육부 교사헌신예배및졸업축하' },
  { src: '/images/community/gallery_969.jpg', label: '교역자및장로님 단체사진' },
  { src: '/images/community/gallery_968.jpg', label: '프로그램활동(쿠키만들기)' },
  { src: '/images/community/gallery_967.jpg', label: '전도부단합대' },
  { src: '/images/community/gallery_966.jpg', label: '겨울성경학교성(둘째날)' },
  { src: '/images/community/gallery_965.jpg', label: '26년 아동부 겨울성경학교(첫날)' },
  { src: '/images/community/gallery_964.jpg', label: '신애교회 영화예배' },
  { src: '/images/community/gallery_963.jpg', label: '26년 신년축복성회' },
  { src: '/images/community/gallery_959.jpg', label: '제10회전교인체육대회점심및폐회식' },
  { src: '/images/community/gallery_958.jpg', label: '제10회전교인체육대회게임' },
  { src: '/images/community/gallery_957.jpg', label: '제10회전교인체육대회예배' },
  { src: '/images/community/gallery_955.jpg', label: '기도실작업과정' },
  { src: '/images/community/gallery_954.jpg', label: '10.04 고구마캐기' },
  { src: '/images/community/gallery_953.jpg', label: '전도사님.김도하생일파티' },
  { src: '/images/community/gallery_943.jpg', label: '추계심방 은혜중에 마침' },
  { src: '/images/community/gallery_930.jpg', label: '상우친구생일파티' },
  { src: '/images/community/gallery_927.jpg', label: '식당에서 만든 먹거리들' },
  { src: '/images/community/gallery_922.jpg', label: '팥빙수. 교육부가 쏩니다~~~' },
  { src: '/images/community/gallery_921.jpg', label: '중보기도팀 회의 후 점심만찬' },
  { src: '/images/community/gallery_920.jpg', label: '김장배추심는날' },
  { src: '/images/community/gallery_919.jpg', label: '새가족수료식' },
  { src: '/images/community/gallery_918.jpg', label: '전도부헌신예배' },
  { src: '/images/community/gallery_917.jpg', label: '아동부부장집들이' },
  { src: '/images/community/gallery_916.jpg', label: '쪽파와무우짱아치나눔' },
  { src: '/images/community/gallery_915.jpg', label: '하계부흥성회' },
  { src: '/images/community/gallery_914.jpg', label: '농작물수확' },
  { src: '/images/community/gallery_909.jpg', label: '패션후르츠에이드' },
  { src: '/images/community/gallery_908.jpg', label: '된장, 고추장 먹거리' },
  { src: '/images/community/gallery_907.jpg', label: '상추로 만든 먹거리' },
  { src: '/images/community/gallery_906.jpg', label: '강낭콩수확' },
  { src: '/images/community/gallery_905.jpg', label: '푸드뱅크(모듬야채및무우후원)' },
  { src: '/images/community/gallery_904.jpg', label: '후원물품(무우)입고' },
  { src: '/images/community/gallery_903.jpg', label: '나에게 하나님이란? (수련회활동)' },
  { src: '/images/community/gallery_901.jpg', label: '교육부 연합수련회' },
  { src: '/images/community/gallery_898.jpg', label: '해남비파열매따기' },
  { src: '/images/community/gallery_897.jpg', label: '6월달전도부활동' },
  { src: '/images/community/gallery_896.jpg', label: '농장부-비온 후 고춧대 정리' },
  { src: '/images/community/gallery_895.jpg', label: '농장부-모듬상추6차후원' },
  { src: '/images/community/gallery_894.jpg', label: '성가대헌신예배' },
  { src: '/images/community/gallery_893.jpg', label: '여전도회-패션후르츠' },
  { src: '/images/community/gallery_892.jpg', label: '교육부 아이스크림 파티' },
  { src: '/images/community/gallery_891.jpg', label: '교육부 연합헌신예배' },
  { src: '/images/community/gallery_884.jpg', label: '마늘작업후휴식' },
  { src: '/images/community/gallery_883.jpg', label: '마늘작업' },
  { src: '/images/community/gallery_882.jpg', label: '해남성전에서예배(마늘작업시)' },
  { src: '/images/community/gallery_881.jpg', label: '상추모듬상자3차나눔' },
  { src: '/images/community/gallery_878.jpg', label: '찬양대회 경품행운상' },
  { src: '/images/community/gallery_877.jpg', label: '찬양대회팀' },
  { src: '/images/community/gallery_876.jpg', label: '전교인찬양대회(준비찬양)' },
  { src: '/images/community/gallery_875.jpg', label: '제15회전교인찬양대회예배' },
  { src: '/images/community/gallery_865.jpg', label: '어버이주일활동' },
  { src: '/images/community/gallery_861.jpg', label: '어린이주일야외예배' },
  { src: '/images/community/gallery_857.jpg', label: '구역성장예배' },
  { src: '/images/community/gallery_856.jpg', label: '전도부미용봉사 "신애헤어방"' },
  { src: '/images/community/gallery_855.jpg', label: '가족전도프로젝트준비' },
  { src: '/images/community/gallery_854.jpg', label: '고기파티' },
  { src: '/images/community/gallery_850.jpg', label: '화단잡초뽑기' },
  { src: '/images/community/gallery_849.jpg', label: '성전내 방음벽시공' },
  { src: '/images/community/gallery_848.jpg', label: '부활주일(특별공연)' },
  { src: '/images/community/gallery_847.jpg', label: '부활절단체사진' },
  { src: '/images/community/gallery_846.jpg', label: '부활절포토존' },
  { src: '/images/community/gallery_845.jpg', label: '부활절아동부활동' },
  { src: '/images/community/gallery_844.jpg', label: '부활절세례식' },
  { src: '/images/community/gallery_839.jpg', label: "'25 과일나무심기" },
  { src: '/images/community/gallery_838.jpg', label: "'25년고난주간 각 구역별 새벽예배특송." },
  { src: '/images/community/gallery_837.jpg', label: "'25년 금요저녁예배(세족식)" },
  { src: '/images/community/gallery_836.jpg', label: '남전도회장 가정 특송' },
  { src: '/images/community/gallery_835.jpg', label: '인도네시아GPDI베데스다교회건축 소식' },
  { src: '/images/community/gallery_834.jpg', label: '의왕시 푸드뱅크 상추 후원' },
  { src: '/images/community/gallery_831.jpg', label: '4월전교인전도대회' },
  { src: '/images/community/gallery_830.jpg', label: '교육부-종려주일 포토존 준비' },
  { src: '/images/community/gallery_829.jpg', label: '남전도헌신예배' },
  { src: '/images/community/gallery_828.jpg', label: '4월생일잔치및새친구' },
  { src: '/images/community/gallery_827.jpg', label: '상추, 당귀, 완두콩심기' },
  { src: '/images/community/gallery_826.jpg', label: '중보기도부신설축하파티' },
  { src: '/images/community/gallery_825.jpg', label: '창고보수작업' },
  { src: '/images/community/gallery_824.jpg', label: '비닐덮기및감자파종' },
  { src: '/images/community/gallery_821.jpg', label: '은혜의 눈이 수북이' },
  { src: '/images/community/gallery_820.jpg', label: '교육부사순절전시회(손바닥물감십자가)' },
  { src: '/images/community/gallery_817.jpg', label: '연못 봄맞이 단장' },
  { src: '/images/community/gallery_812.jpg', label: '2025년 춘계대심방' },
  { src: '/images/community/gallery_807.jpg', label: '농장부 비닐및퇴비작업' },
  { src: '/images/community/gallery_806.jpg', label: '농장부헌신예배' },
  { src: '/images/community/gallery_805.jpg', label: '인도네시아GPDI베데스다교회건축진행과정' },
  { src: '/images/community/gallery_804.jpg', label: '사순절본당꽃꽂이' },
  { src: '/images/community/gallery_803.jpg', label: '인도네시아GPDI베데스다교회건축 기공식' },
  { src: '/images/community/gallery_802.jpg', label: '아동부, 중.고등부전도사임명' },
  { src: '/images/community/gallery_801.jpg', label: '사순절기간매일말씀읽고,묵상하기' },
  { src: '/images/community/gallery_800.jpg', label: '2025년 졸업축하및 교사헌신예배' },
  { src: '/images/community/gallery_798.jpg', label: '아동부친구들 부목사님 사랑이 가득담긴 세뱃돈받기' },
  { src: '/images/community/gallery_797.jpg', label: '설명절 전부침' },
  { src: '/images/community/gallery_796.jpg', label: '전도부 단합대회(화천)' },
  { src: '/images/community/gallery_795.jpg', label: '전도대회' },
  { src: '/images/community/gallery_794.jpg', label: '겨울성경학교 눈썰매장놀이활동' },
  { src: '/images/community/gallery_793.jpg', label: '전도부화천심방(서장원안수집사님본가)' },
  { src: '/images/community/gallery_792.jpg', label: '전교인 민속놀이 한마당' },
  { src: '/images/community/gallery_791.jpg', label: '입학선물증정' },
  { src: '/images/community/gallery_790.jpg', label: '한상욱전도사님과 함께' },
  { src: '/images/community/gallery_788.jpg', label: '2025년 신년축복성회' },
  { src: '/images/community/gallery_576.jpg', label: '드라이브스루 배달' },
  { src: '/images/community/gallery_524.jpg', label: '만남데이트' },
  { src: '/images/community/gallery_523.jpg', label: '장미꽃울타리만들기' },
  { src: '/images/community/gallery_522.jpg', label: '불판제작및 성전내,외부환경미화' },
  { src: '/images/community/gallery_521.jpg', label: '본당피아노교체' },
  { src: '/images/community/gallery_520.jpg', label: '음향기기교체' },
  { src: '/images/community/gallery_519.jpg', label: '교육부스승의날 축하모임' },
  { src: '/images/community/gallery_518.jpg', label: '어버이날(카네이션석고방향제만들기)' },
  { src: '/images/community/gallery_517.jpg', label: 'LED카네이션케익만들기' },
  { src: '/images/community/gallery_516.jpg', label: '어린이날축하선물' },
  { src: '/images/community/gallery_515.jpg', label: '연합권사회 화단잡초제거및 삼겹살파티' },
  { src: '/images/community/gallery_500.jpg', label: '부활절 꽃꽂이와포토존' },
  { src: '/images/community/gallery_496.jpg', label: '부활절계란전시회' },
  { src: '/images/community/gallery_488.jpg', label: '밭계단만들기-권*진집사외회원들' },
  { src: '/images/community/gallery_487.jpg', label: '감자심기' },
  { src: '/images/community/gallery_463.jpg', label: '2020.02.09토지매입후예배' },
  { src: '/images/community/gallery_462.jpg', label: '청년부(스키장)' },
  { src: '/images/community/gallery_461.jpg', label: '청년부단합회' },
  { src: '/images/community/gallery_460.jpg', label: '교육부장학수여및 졸업예배' },
  { src: '/images/community/gallery_441.jpg', label: '2020.1.18직분자교육' },
  { src: '/images/community/gallery_421.jpg', label: '흥부와놀부의성탄절' },
  { src: '/images/community/gallery_420.jpg', label: '창조.타락.구원(교육부연합)' },
  { src: '/images/community/gallery_419.jpg', label: '"천사들의 노래가"' },
  { src: '/images/community/gallery_418.jpg', label: '워십-찬양이 언제나 넘치면' },
  { src: '/images/community/gallery_417.jpg', label: '성탄케익컷팅식및예배' },
  { src: '/images/community/gallery_416.jpg', label: '성탄특별활동"떡매치기"' },
  { src: '/images/community/gallery_415.jpg', label: '산타의 선물' },
  { src: '/images/community/gallery_412.jpg', label: '고구마굽기와장작패기도전' },
  { src: '/images/community/gallery_409.jpg', label: '용인산울교회심방' },
  { src: '/images/community/gallery_404.jpg', label: '최*정집사미용봉사' },
  { src: '/images/community/gallery_397.jpg', label: '중.고등부교육및만남데이트' },
  { src: '/images/community/gallery_396.jpg', label: '연합여전도(만두)' },
  { src: '/images/community/gallery_395.jpg', label: '교육관땔감준비' },
  { src: '/images/community/gallery_394.jpg', label: "'19년2학기종강예배" },
  { src: '/images/community/gallery_393.jpg', label: '전도부국화빵개시' },
  { src: '/images/community/gallery_392.jpg', label: '2019.11.19크리스마스트리' },
  { src: '/images/community/gallery_386.jpg', label: '2019년김장준비' },
  { src: '/images/community/gallery_385.jpg', label: '2019.11.3세례,입교,학습' },
  { src: '/images/community/gallery_384.jpg', label: '2019.10.30구역장 단합회' },
  { src: '/images/community/gallery_383.jpg', label: '2019.10.27정기총회' },
  { src: '/images/community/gallery_382.jpg', label: '월미도테마파크(토요활동)' },
  { src: '/images/community/gallery_381.jpg', label: '2019.10.26연합여전도회바자회' },
  { src: '/images/community/gallery_380.jpg', label: '2019.10.13중.고등부사진전시회' },
  { src: '/images/community/gallery_339.jpg', label: '제7회전교인체육대회' },
  { src: '/images/community/gallery_338.jpg', label: '문화가있는 날' },
  { src: '/images/community/gallery_337.jpg', label: '성가대 헌신예배' },
  { src: '/images/community/gallery_336.jpg', label: '토요활동에버랜드' },
  { src: '/images/community/gallery_335.jpg', label: '김*셉전도사송별회' },
  { src: '/images/community/gallery_334.jpg', label: '2남전도헌신예배' },
  { src: '/images/community/gallery_333.jpg', label: '2019.9.7임직식' },
  { src: '/images/community/gallery_324.jpg', label: '2019.8.27군산심방후 친목' },
  { src: '/images/community/gallery_320.jpg', label: '2019.8.18구역성장예배' },
  { src: '/images/community/gallery_319.jpg', label: '산티아고순례길' },
  { src: '/images/community/gallery_315.jpg', label: '중.고등부수련회8.5~7일' },
  { src: '/images/community/gallery_310.jpg', label: '2019하계축복성회' },
  { src: '/images/community/gallery_309.jpg', label: '중등부 물놀이' },
  { src: '/images/community/gallery_305.jpg', label: '2019.07.21청년부헌신예배' },
  { src: '/images/community/gallery_304.jpg', label: '2019.07.21.중.고등부 헌신예배' },
  { src: '/images/community/gallery_298.jpg', label: '2019.7.13워터슬라이드' },
  { src: '/images/community/gallery_297.jpg', label: '7월중농장물수확' },
  { src: '/images/community/gallery_296.jpg', label: '2019.7.13-14여름성경학교' },
  { src: '/images/community/gallery_295.jpg', label: '2019.7.10교육관개관예배' },
  { src: '/images/community/gallery_289.jpg', label: '연꽃축제2019.7.7' },
  { src: '/images/community/gallery_284.jpg', label: '생일파티및특별활동2019.6.30' },
  { src: '/images/community/gallery_283.jpg', label: '교사헌신예배2019.6.30' },
  { src: '/images/community/gallery_282.jpg', label: '교육관개관식및 출입문컷팅식2019.6.30' },
  { src: '/images/community/gallery_275.jpg', label: '제직회헌신예배(2019.6.23)' },
  { src: '/images/community/gallery_274.jpg', label: '콩심기(2019.6.21)' },
  { src: '/images/community/gallery_270.jpg', label: '교육관 담장공사(2019.06.19)' },
  { src: '/images/community/gallery_264.jpg', label: '성막견학2019.06.15' },
  { src: '/images/community/gallery_261.jpg', label: '2019년안수집사,권사임직자교육' },
  { src: '/images/community/gallery_260.jpg', label: '75세이상 어르신들야유회(전도부)' },
  { src: '/images/community/gallery_252.jpg', label: '제직회주관고기파티2019.05.26' },
  { src: '/images/community/gallery_232.jpg', label: '5월토요활동' },
  { src: '/images/community/gallery_231.jpg', label: '전교인찬양대회' },
  { src: '/images/community/gallery_230.jpg', label: '세례자(김*자성도)' },
  { src: '/images/community/gallery_229.jpg', label: '성막견학' },
  { src: '/images/community/gallery_228.jpg', label: '어린이날' },
  { src: '/images/community/gallery_227.jpg', label: '부활절공연' },
  { src: '/images/community/gallery_226.jpg', label: '부활절포토존' },
  { src: '/images/community/gallery_225.jpg', label: '부활절연합예배' },
  { src: '/images/community/gallery_224.jpg', label: '세족식' },
  { src: '/images/community/gallery_223.jpg', label: '부활절 준비' },
  { src: '/images/community/gallery_198.jpg', label: '파자마파티' },
  { src: '/images/community/gallery_186.jpg', label: '2019년신년축복성회(설교)' },
  { src: '/images/community/gallery_185.jpg', label: '2019년신년축복성회(부서별준비찬양)' },
  { src: '/images/community/gallery_184.jpg', label: '청년부 스키장' },
  { src: '/images/community/gallery_170.jpg', label: '크리스마스나무주위에서춤추는 것' },
  { src: '/images/community/gallery_169.jpg', label: '가브리엘의 크리스마스' },
  { src: '/images/community/gallery_168.jpg', label: '성탄예배사회와 워십' },
  { src: '/images/community/gallery_166.jpg', label: '워십-주의친절한 팔에안기세' },
  { src: '/images/community/gallery_165.jpg', label: 'This christmas' },
  { src: '/images/community/gallery_164.jpg', label: '성탄축하예배' },
  { src: '/images/community/gallery_158.jpg', label: '성탄포토존' },
  { src: '/images/community/gallery_157.jpg', label: '연합남전도회식' },
  { src: '/images/community/gallery_155.jpg', label: '추수감사절예배' },
  { src: '/images/community/gallery_154.jpg', label: 'Ilove jesus' },
  { src: '/images/community/gallery_153.jpg', label: '"고마워 고마워" 찬양' },
  { src: '/images/community/gallery_152.jpg', label: '찬양' },
  { src: '/images/community/gallery_151.jpg', label: '태권무(장*우외2명)' },
  { src: '/images/community/gallery_150.jpg', label: '내영혼이 은총입어(워십팀)' },
  { src: '/images/community/gallery_149.jpg', label: '"사랑" 무언극' },
  { src: '/images/community/gallery_148.jpg', label: '"무화가 잎이 마르고" 율동' },
  { src: '/images/community/gallery_147.jpg', label: '성찬식' },
  { src: '/images/community/gallery_146.jpg', label: '입교세례자' },
  { src: '/images/community/gallery_145.jpg', label: '유아세례' },
  { src: '/images/community/gallery_130.jpg', label: '연합남전도회 고기파티(2018.11.3)' },
  { src: '/images/community/gallery_127.jpg', label: '추수감사절' },
  { src: '/images/community/gallery_126.jpg', label: '성탄추리' },
  { src: '/images/community/gallery_125.jpg', label: '김장김치(2018.11.10이후)' },
  { src: '/images/community/gallery_113.jpg', label: "18'10.3전교인체육대회(고천중)" },
  { src: '/images/community/gallery_112.jpg', label: "18'9.30.문화가있는날(포토존)" },
  { src: '/images/community/gallery_111.jpg', label: "18'9.30.문화가있는날(중.고공연)" },
  { src: '/images/community/gallery_110.jpg', label: "18'9.30.문화가있는날(청년부공연)" },
  { src: '/images/community/gallery_108.jpg', label: "18'9.30.문화가있는날(청년부불량식품)" },
  { src: '/images/community/gallery_107.jpg', label: "18'9.30.문화가있는날(중,고복고)" },
  { src: '/images/community/gallery_104.jpg', label: '추석맞이 백운산 산행' },
  { src: '/images/community/gallery_103.jpg', label: '해바라기 꽃길' },
  { src: '/images/community/gallery_97.jpg', label: '의왕시 찬양제관람' },
  { src: '/images/community/gallery_96.jpg', label: '운두령횟집식사' },
  { src: '/images/community/gallery_95.jpg', label: '강원도양떼목장' },
  { src: '/images/community/gallery_94.jpg', label: '강원도경포해수욕장' },
  { src: '/images/community/gallery_93.jpg', label: '2018.2학기개강예배(장학생들)' },
  { src: '/images/community/gallery_91.jpg', label: '이색성경퀴즈(토요활동)' },
  { src: '/images/community/gallery_89.jpg', label: '잉어의식사한끼' },
  { src: '/images/community/gallery_75.jpg', label: '심현보집사 준비찬양인도' },
  { src: '/images/community/gallery_74.jpg', label: '예배후 자유시간' },
  { src: '/images/community/gallery_72.jpg', label: '중.고등부-생일파티' },
  { src: '/images/community/gallery_71.jpg', label: '연합남전도회-헌신예배준비' },
  { src: '/images/community/gallery_70.jpg', label: '제주도수련회' },
  { src: '/images/community/gallery_69.jpg', label: '중.고등부-토요활동' },
  { src: '/images/community/gallery_68.jpg', label: '권사회-백운사산행' },
  { src: '/images/community/gallery_67.jpg', label: '여전도회-백운사산행' },
  { src: '/images/community/gallery_66.jpg', label: '여전도-벼룩시장' },
  { src: '/images/community/gallery_65.jpg', label: '제직회-25인승번호판(2018.8.31)' },
  { src: '/images/community/gallery_64.jpg', label: '연합여전도회추석명절선물판매 중- 금액확인' },
  { src: '/images/community/gallery_63.jpg', label: '남전도-섬김과 봉사의 모습' },
  { src: '/images/community/gallery_62.jpg', label: '주일봉헌송' },
  { src: '/images/community/gallery_61.jpg', label: '성가대찬양' },
  { src: '/images/community/gallery_59.jpg', label: '청년부-문화가있는날(주제:꽃)' },
  { src: '/images/community/gallery_58.jpg', label: '민속촌-토요활동' },
  { src: '/images/community/gallery_57.jpg', label: '청년부찬양인도' },
  { src: '/images/community/gallery_56.jpg', label: '전교인 성경퀴즈대회' },
  { src: '/images/community/gallery_55.jpg', label: '중.고등부수련회후원금마련회' },
  { src: '/images/community/gallery_54.jpg', label: '중.고등부야유예배' },
  { src: '/images/community/gallery_53.jpg', label: '전도부(75세어르신봄나들이)' },
  { src: '/images/community/gallery_52.jpg', label: '전도부(토요전도활동)' },
  { src: '/images/community/gallery_49.jpg', label: '제직회(패션쇼및바자회)' },
  { src: '/images/community/gallery_46.jpg', label: '연못' },
  { src: '/images/community/gallery_45.jpg', label: '권사회김장배추심기' },
  { src: '/images/community/gallery_44.jpg', label: '농장-감자수확' },
  { src: '/images/community/gallery_43.jpg', label: '권사회특별바자회' },
  { src: '/images/community/gallery_42.jpg', label: '연꽃축제' },
  { src: '/images/community/gallery_41.jpg', label: '신애교회워터슬라이드' },
  { src: '/images/community/gallery_40.jpg', label: '여름성경학교' },
  { src: '/images/community/gallery_37.jpg', label: '군산진리가있는교회방문' },
  { src: '/images/community/gallery_36.jpg', label: '2018.5.13전교인찬양대회' },
  { src: '/images/community/gallery_23.jpg', label: '성경대학단합대회' },
  { src: '/images/community/gallery_22.jpg', label: '2018.5.15.스승의날' },
  { src: '/images/community/gallery_21.jpg', label: '성경대학MT' },
  { src: '/images/community/gallery_18.jpg', label: '성경대학제1기졸업및수료식' },
]

export default function Gallery() {
  const [lightbox, setLightbox] = useState(null)
  const [page, setPage] = useState(1)
  const totalPages = Math.ceil(photos.length / PER_PAGE)
  const slice = photos.slice((page - 1) * PER_PAGE, page * PER_PAGE)

  return (
    <SubLayout section="교제와 나눔" menus={menus} title="행사갤러리">
      <div style={{ marginBottom: '12px', fontSize: '0.82rem', color: '#9ca3af', textAlign: 'right' }}>전체 {photos.length}장</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px' }}>
        {slice.map((p, i) => {
          const globalIdx = (page - 1) * PER_PAGE + i
          return (
            <div key={globalIdx} onClick={() => setLightbox(globalIdx)} style={{ borderRadius: '12px', overflow: 'hidden', cursor: 'pointer', border: '1px solid #eaecf0' }}>
              <div style={{ aspectRatio: '4/3', overflow: 'hidden' }}>
                <img src={p.src} alt={p.label} style={{ width: '100%', height: '100%', objectFit: 'cover', transition: 'transform 0.3s' }}
                  onMouseEnter={e => e.target.style.transform = 'scale(1.05)'}
                  onMouseLeave={e => e.target.style.transform = 'scale(1)'}
                />
              </div>
              <div style={{ padding: '8px 10px', background: '#fff' }}>
                <p style={{ fontSize: '0.75rem', color: '#374151', fontWeight: 500, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{p.label}</p>
              </div>
            </div>
          )
        })}
      </div>

      <Pagination page={page} totalPages={totalPages} onPage={(p) => { setPage(p); setLightbox(null) }} />

      {lightbox !== null && (
        <div onClick={() => setLightbox(null)} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.88)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '20px' }}>
          <div onClick={e => e.stopPropagation()} style={{ position: 'relative', maxWidth: '900px', width: '100%' }}>
            <img src={photos[lightbox].src} alt="" style={{ width: '100%', borderRadius: '12px' }} />
            <p style={{ textAlign: 'center', color: 'rgba(255,255,255,0.7)', fontSize: '0.85rem', marginTop: '12px' }}>{photos[lightbox].label}</p>
            {lightbox > 0 && <button onClick={e => { e.stopPropagation(); setLightbox(lightbox - 1) }} style={{ position: 'absolute', left: '-48px', top: '50%', transform: 'translateY(-50%)', background: 'rgba(255,255,255,0.15)', border: 'none', borderRadius: '50%', width: '40px', height: '40px', color: '#fff', fontSize: '1.3rem', cursor: 'pointer' }}>‹</button>}
            {lightbox < photos.length - 1 && <button onClick={e => { e.stopPropagation(); setLightbox(lightbox + 1) }} style={{ position: 'absolute', right: '-48px', top: '50%', transform: 'translateY(-50%)', background: 'rgba(255,255,255,0.15)', border: 'none', borderRadius: '50%', width: '40px', height: '40px', color: '#fff', fontSize: '1.3rem', cursor: 'pointer' }}>›</button>}
            <button onClick={() => setLightbox(null)} style={{ position: 'absolute', top: '-40px', right: 0, background: 'none', border: 'none', color: '#fff', fontSize: '1.5rem', cursor: 'pointer' }}>✕</button>
          </div>
        </div>
      )}
    </SubLayout>
  )
}
